Repository chiku0112/Get-Set-Foss_Design, pull requests merged in 2019-11, with the labels that each got.

#9 app prototype by designer lav
  WhatsApp Image 2019-11-05 at 21.38.01.jpeg
Labels: easy, getsetfoss2019

#8 Add files via upload
  web1.jfif
  web2.jfif
Labels: easy, getsetfoss2019

#10 app prototype design by moin
  IMG_20191106_220423.JPG
Labels: easy, getsetfoss2019

#12 App Prototype
  App Prototype
Labels: easy, getsetfoss2019

#13 app prototype
  app prototype
Labels: easy, getsetfoss2019

#14 App Prototype 1
  App Prototype 1
Labels: easy, getsetfoss2019

#16 KANUPRIYA app prototype 1
  KANUPRIYA app prototype
Labels: easy, getsetfoss2019

#22 Web Prototype
  1.png
  2.png
  3.png
  4.png
  Screenshot (48).png
  Screenshot (49).png
  Screenshot (50).png
  Screenshot (51).png
Labels: getsetfoss2019, hard

#11 Add files via upload
  design/1.png
  design/2.png
  design/3.png
  design/4.png
  design/5.png
  design/6.png
  design/7.png
  design/Screenshot (41).png
  design/Screenshot (42).png
  design/Screenshot (43).png
Labels: getsetfoss2019, hard

#28 Web Prototype (Task 1)
  Web 1 Nishan.jpg
Labels: easy, getsetfoss2019

#29 App Prototype (Task 1)
  App1 Nishan/App1 Nishan.jpg
  App1 Nishan/App1(2) Nishan.jpg
Labels: easy, getsetfoss2019

#27 initial commit
  newlink.txt
Labels: getsetfoss2019, pro

#26 initial commit
  webpro.txt
Labels: getsetfoss2019, pro

#15 boon app prototype
  boon app prototype
Labels: easy, getsetfoss2019

#40 Added Rough Sketch of App Prototype
  WhatsApp Image 2019-11-15 at 1.13.49 AM.jpeg
Labels: easy, getsetfoss2019

#41 Added lo fi Wireframes
  Screenshot (193).png
  Screenshot (194).png
  Screenshot (195).png
  Screenshot (196).png
  Screenshot (197).png
Labels: getsetfoss2019, pro

#42 Added App prototype link in a file
  AppPrototype
Labels: getsetfoss2019, pro

#30 Web Prototype 3
  Web Prototype 3
Labels: getsetfoss2019, medium

#43 solved issue 4 web prototype (task 1)
  IMG_20191117_213921.jpg
Labels: easy, getsetfoss2019

#47 App prototype by moin (task 2)
  Screenshot (20).png
  Screenshot (21).png
  Screenshot (22).png
  Screenshot (23).png
  Screenshot (24).png
  Screenshot (25).png
Labels: getsetfoss2019, hard

#48 App prototype by moin(task 3)
  Figma_Moin_app.txt
Labels: getsetfoss2019, pro

#49 web prototype by moin (task 1)
  web proto type.pdf
Labels: easy, getsetfoss2019

#50 web prototype by moin (task 2)
  web prototype/Screenshot (26).png
  web prototype/Screenshot (27).png
  web prototype/Screenshot (28).png
  web prototype/Screenshot (29).png
  web prototype/Screenshot (30).png
  web prototype/Screenshot (31).png
Labels: getsetfoss2019, hard

#51 web prototype by moin (task 3)
  web_prototype_3.txt
Labels: getsetfoss2019, pro

#61 App Prototype (Task 2) #2
  NScreenshot (57).png
  NScreenshot (58).png
  NScreenshot (59).png
  NScreenshot (60).png
  NScreenshot (61).png
  NScreenshot (62).png
  NScreenshot (63).png
Labels: getsetfoss2019, hard

#72 Web Prototype (Task 3)
  Web#ByNishan.md
Labels: getsetfoss2019, pro

#67 App Prototype (Task 1) #1
  App1 Yogesh.jpg
Labels: easy, getsetfoss2019

#68 App Prototype (Task 2) #2
  App Prototype yk1ax/One stop for all the foodies-1.jpg
  App Prototype yk1ax/One stop for all the foodies-2.jpg
  App Prototype yk1ax/One stop for all the foodies-3.jpg
  App Prototype yk1ax/One stop for all the foodies-4.jpg
  App Prototype yk1ax/One stop for all the foodies-5.jpg
  App Prototype yk1ax/One stop for all the foodies-6.jpg
  App Prototype yk1ax/One stop for all the foodies-7.jpg
  App Prototype yk1ax/One stop for all the foodies-8.jpg
Labels: getsetfoss2019, hard

#75 Web Prototype (Task 1) #4
  Web 1920 – 1.png
Labels: easy, getsetfoss2019

#78 Web Prototype (Task 2) #5
  Web2/Page 1.png
  Web2/Page 2.png
  Web2/Page 3.png
Labels: getsetfoss2019, medium

#80 Web Prototype (Task 3) #6
  web3yk1ax.md
Labels: getsetfoss2019, hard

#63 Weather UI
  Weather UI(Nishan).png
Labels: getsetfoss2019, medium

#70 Weather ui ui
  Screenshot from 2019-11-21 03-48-28.png
Labels: easy, getsetfoss2019

#73 WEATHER UI by MOIN
  Screenshot (34).png
Labels: getsetfoss2019, medium

#74 Weather UI #54
  Screenshot Weather UI.png
Labels: getsetfoss2019, hard

#79 AP Weather UI
  Calendar UI
  Weather App UI
Labels: getsetfoss2019, medium

#56 Ayushi Lodhi App Prototype 2
  AppPrototype2
  New Doc 2019-11-15 17.15.37.pdf
Labels: getsetfoss2019, hard

#69 Calendar UI #53
  Calendar UI.png
  Screenshot (57).png
Labels: getsetfoss2019, medium

#76 calender-ui-ui
  Screenshot from 2019-11-22 04-08-02.png
Labels: getsetfoss2019, medium

#81 calender UI
  Screenshot (66).png
Labels: getsetfoss2019, medium

#64 Calendar UI
  Calendar by Nishan.png
Labels: getsetfoss2019, medium

#83 Web Prototype (Task 2)
  Screenshot (67).png
  Screenshot (68).png
  Screenshot (69).png
  Screenshot (70).png
Labels: getsetfoss2019, medium

#84 Kop105 app prototype (task 2)
  Screenshot (71).png
  Screenshot (72).png
  Screenshot (73).png
Labels: getsetfoss2019, medium

#95 Web Prototype Link in a file
  HarshitFigmaWeb.txt
Labels: getsetfoss2019, pro

#94 Added lo fi wireframes of Web Prototype
  Screenshot (221).png
  Screenshot (222).png
  Screenshot (223).png
  Screenshot (224).png
Labels: getsetfoss2019, pro

#93 Added Rough Sketch Of Web Prototype
  WhatsApp Image 2019-11-23 at 8.25.17 PM.jpeg
Labels: easy, getsetfoss2019

#92 Create CALENDAR
  CALENDAR
Labels: easy, getsetfoss2019

#91 Create WEATHER
  WEATHER
Labels: getsetfoss2019, medium

#90 new updated app prototype (task 3)
  app prototype task 3.txt
Labels: getsetfoss2019, pro

#88 Web Prototype Task 1 library sample
  IMG_20191123_185746.jpg
Labels: easy, getsetfoss2019

#86 App Prototype (Task 3) #3
  app_prot_yk1ax.md
Labels: getsetfoss2019, pro

#97 ui calendar
  Screenshot (38).png
Labels: getsetfoss2019, medium

#96 again added task 3 web prototype
  web library task 3.txt
Labels: getsetfoss2019, hard
